export default {
  plantNum: 3,

  sliders: [
    {
      label: "Profundidad de recursión",
      key: "recursionDepth",
      min: 0,
      init: 7,
      max: 7,
      step: 1,
      precision: 0,
    },
    {
      label: "Tamaño",
      key: "size",
      min: 0,
      init: 100,
      max: 200,
      step: 1,
      precision: 0,
    },
    {
      label: "Longitud mínima de rama",
      key: "branchMinLength",
      min: 0.0,
      init: 1.0,
      max: 10.0,
      step: 0.1,
      precision: 1,
    },
    {
      label: "Coeficiente de disminución A",
      key: "decCoeffA",
      min: 0.0,
      init: 0.9,
      max: 1.0,
      step: 0.01,
      precision: 2,
    },
    {
      label: "Coeficiente de disminución B",
      key: "decCoeffB",
      min: 0.0,
      init: 0.9,
      max: 1.0,
      step: 0.01,
      precision: 2,
    },
    {
      label: "Grosor",
      key: "thickness",
      min: 0.0,
      init: 1.0,
      max: 2.0,
      step: 0.01,
      precision: 2,
    },
    {
      label: "Ángulo α",
      key: "alpha",
      min: 0.0,
      init: Math.PI / 8,
      max: Math.PI / 4,
      step: 0.001,
      precision: 3,
    },
    {
      label: "Ángulo Δα",
      key: "deltaAlpha",
      min: -Math.PI / 8,
      init: 0,
      max: Math.PI / 8,
      step: 0.001,
      precision: 3,
    },
    {
      label: "Ángulo Δβ",
      key: "deltaBeta",
      min: -Math.PI / 8,
      init: 0,
      max: Math.PI / 8,
      step: 0.001,
      precision: 3,
    },
    {
      label: "Ángulo γ",
      key: "gamma",
      min: -Math.PI / 4,
      init: 0,
      max: Math.PI / 4,
      step: 0.001,
      precision: 3,
    },
    {
      label: "Aleatoriedad",
      key: "randomization",
      min: 0.0,
      init: 2.0,
      max: 10.0,
      step: 0.01,
      precision: 2,
    },
    {
      label: "Tono",
      key: "hue",
      min: 0,
      init: 180,
      max: 360,
      step: 1,
      precision: 0,
    },
    {
      label: "Saturación",
      key: "saturation",
      min: 0,
      init: 100,
      max: 100,
      step: 1,
      precision: 0,
    },
    {
      label: "Brillo",
      key: "brightness",
      min: 0.0,
      init: 1.0,
      max: 1.0,
      step: 0.01,
      precision: 2,
    },
  ],
};
